name: Mirror to Bitbucket Repo

on: [ push, delete, create ]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE2 }}
        with:
          # source-repo: 'git@github.com:wearerequired/swisscom-magazine.git'
          # destination-repo: 'git@bitbucket.org:wearerequired/git-mirror-action.git'
          source-repo: 'git@github.com:just-wkj/alfredSettings.git'
          destination-repo: 'git@gitee.com:justwkj/alfredSettings.git'
